name: SharonTest1
favicon: null
layout_spectrum: 0.15290145482867956
typography_spectrum: 0.7579292436130345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00235d'
    - '#8cc63e'
    - '#f8981d'
    - '#52bcec'
    - '#415985'
  brandStrength: 0.3272519011516124
  lightness: 0.34553744550794363
  saturation: 0.09109654789790511
  rhythmicContrast: 0.5373887366149575
purpose: []
